# Generated by Django 5.2.4 on 2025-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturent_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('phone_number_1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
