# Generated by Django 5.2.4 on 2025-08-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone_number_2',
            new_name='twilio_number',
        ),
    ]
