# Generated by Django 5.2.4 on 2025-08-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_phone_number_2_restaurant_twilio_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='iban',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tax_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
