# Generated by Django 5.2.4 on 2025-09-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='twilio_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
