# Generated by Django 5.2.4 on 2025-09-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_twilio_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='total_vapi_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
