# Generated by Django 5.2.4 on 2025-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_restaurant_total_vapi_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="forword_mode",
            field=models.CharField(
                blank=True,
                help_text="Specify the restaurant's forwarding mode (e.g., auto, manual, off)",
                max_length=50,
                null=True,
            ),
        ),
    ]
