# Generated by Django 5.2.4 on 2025-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_openandclosetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="openandclosetime",
            name="is_closed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Mark true if the restaurant is closed on this day",
                null=True,
            ),
        ),
    ]
