# Generated by Django 5.2.4 on 2025-09-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0007_restaurant_total_vapi_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('service', 'Service'), ('reservation', 'Reservation'), ('order', 'Order')], max_length=100, null=True)),
                ('call_date_utc', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('recording', models.CharField(max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('assistant_id', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('callback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_number', models.CharField(max_length=20, unique=True)),
                ('twilio_account_sid', models.CharField(max_length=500)),
                ('twilio_auth_token', models.CharField(max_length=500)),
                ('vapi_phone_number_id', models.CharField(max_length=500, unique=True)),
                ('assistant_id', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistance', to='restaurants.restaurant')),
            ],
        ),
    ]
