# Generated by Django 5.2.4 on 2025-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIvapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callinformations',
            name='callback_track',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
