# Generated by Django 5.2.4 on 2025-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIvapi', '0002_callinformations_callback_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='callinformations',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
