# Generated by Django 5.2.4 on 2025-10-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIvapi', '0003_callinformations_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='twilio_account_sid',
            new_name='twilio_account_sid_encrypted',
        ),
        migrations.RenameField(
            model_name='assistance',
            old_name='twilio_auth_token',
            new_name='twilio_auth_token_encrypted',
        ),
    ]
