# Generated by Django 5.2.4 on 2025-10-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AIvapi",
            "0004_rename_twilio_account_sid_assistance_twilio_account_sid_encrypted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assistance",
            name="speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Speech speed multiplier (e.g. 0.8 = slower, 1.2 = faster).",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assistance",
            name="voice",
            field=models.CharField(
                blank=True,
                help_text="Voice ID or name for the AI assistant.",
                max_length=100,
                null=True,
            ),
        ),
    ]
