# Generated by Django 5.2.4 on 2025-10-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIvapi", "0005_assistance_speed_assistance_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistance",
            name="speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=1.0,
                help_text="Speech speed multiplier (e.g. 0.7 = slower, 1.2 = faster).",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assistance",
            name="voice",
            field=models.CharField(
                blank=True,
                default="matilda",
                help_text="Voice ID or name for the AI assistant.",
                max_length=100,
                null=True,
            ),
        ),
    ]
