# Generated by Django 5.2.4 on 2025-09-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0006_alter_restaurant_twilio_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_number', models.CharField(max_length=20, unique=True)),
                ('twilio_account_sid', models.CharField(max_length=500)),
                ('twilio_auth_token', models.CharField(max_length=500)),
                ('vapi_phone_number_id', models.CharField(max_length=500, unique=True)),
                ('assistant_id', models.CharField(max_length=500, unique=True)),
                ('tool1_id', models.CharField(blank=True, max_length=500, null=True)),
                ('tool2_id', models.CharField(blank=True, max_length=500, null=True)),
                ('tool3_id', models.CharField(blank=True, max_length=500, null=True)),
                ('tool4_id', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistance', to='restaurants.restaurant')),
            ],
        ),
    ]
