# Generated by Django 5.2.4 on 2025-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('call_date_utc', models.DateTimeField()),
                ('duration_seconds', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('recording', models.CharField(max_length=1000)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
