# Generated by Django 5.2.4 on 2025-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0002_callinformations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinformations',
            name='address',
        ),
        migrations.RemoveField(
            model_name='callinformations',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='callinformations',
            name='email',
        ),
        migrations.AddField(
            model_name='callinformations',
            name='assistant_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='callinformations',
            name='vapi_phone_number_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
