# Generated by Django 5.2.4 on 2025-08-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/package_images/')),
                ('recurring', models.BooleanField(default=True)),
                ('amount', models.FloatField(help_text='In dollars (e.g., 9.99)')),
                ('billing_interval', models.CharField(help_text='e.g., day, month, year', max_length=20)),
                ('interval_count', models.IntegerField(default=1, help_text='Number of intervals (e.g., every 6 months = 6)')),
                ('price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('active', 'Active')], default='active', max_length=10)),
            ],
        ),
    ]
