# Generated by Django 5.2.4 on 2025-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_stripeeventlog_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='vapi_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
