# Generated by Django 5.2.4 on 2025-12-01 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0010_openandclosetime_is_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extras", models.CharField(max_length=200)),
                ("extras_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
        ),
    ]
