# Generated by Django 5.2.4 on 2025-08-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_adminapproved_user_approved_user_extrapassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner')], default='Owner', max_length=10),
        ),
    ]
