# Generated by Django 5.2.4 on 2025-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/support_files/'),
        ),
    ]
