# Generated by Django 5.2.4 on 2025-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preparation_time',
            field=models.DurationField(blank=True, help_text='Duration format: hh:mm:ss', null=True),
        ),
    ]
