# Generated by Django 5.2.4 on 2025-11-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0003_alter_customer_email"),
        ("restaurants", "0010_openandclosetime_is_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_summary", models.TextField(blank=True, null=True)),
                ("callback_done", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("service", "Service"), ("callback", "Callback")],
                        default="service",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="customer.customer",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
        ),
    ]
