# Generated by Django 5.2.4 on 2025-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='callback_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('callback', 'Callback')], default='service', max_length=10),
        ),
    ]
