# Generated by Django 5.2.4 on 2025-10-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0007_restaurant_total_vapi_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalcode', models.CharField(max_length=50)),
                ('estimated_delivery_time', models.CharField(max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_managements', to='restaurants.restaurant')),
            ],
        ),
    ]
