# Generated by Django 5.2.4 on 2025-10-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0001_initial'),
        ('order', '0003_order_allergy_order_discount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='delivery_management.areamanagement'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='delivery', help_text='Select whether the order is for pickup or delivery', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
