# Generated by Django 5.2.4 on 2025-10-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0001_initial'),
        ('order', '0004_order_delivery_area_order_delivery_area_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='delivery_management.areamanagement'),
        ),
    ]
