# Generated by Django 5.2.4 on 2025-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_order_address_remove_order_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("incoming", "Incoming"),
                    ("in_preparation", "In Preparation"),
                    ("out_for_delivery", "Out for delivery"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
