# Generated by Django 5.2.4 on 2025-08-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text="Customer's phone number", max_length=15, null=True)),
                ('guest_no', models.IntegerField(help_text='Number of guests in the reservation')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], default='pending', help_text='Reservation status', max_length=20)),
                ('date', models.DateField(help_text='Reservation date')),
                ('from_time', models.TimeField(help_text='Reservation start time (hh:mm:ss format)')),
                ('to_time', models.TimeField(help_text='Reservation end time (hh:mm:ss format)')),
                ('email', models.EmailField(blank=True, help_text="Customer's email address (optional)", max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(help_text='Table reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='table.table')),
            ],
        ),
    ]
