# Generated by Django 5.2.4 on 2025-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('walk-in', 'Walk-in'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='reserved', help_text='Reservation status', max_length=20),
        ),
    ]
