# Generated by Django 5.2.4 on 2025-09-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='allergy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
