# Generated by Django 5.2.4 on 2025-10-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_reservation_address_reservation_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
