# Generated by Django 5.2.4 on 2025-11-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_email"),
        ("table", "0005_reservation_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer who made the reservation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="customer.customer",
            ),
        ),
    ]
