# Generated by Django 5.2.4 on 2025-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0006_remove_reservation_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="allergy",
        ),
        migrations.AddField(
            model_name="reservation",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Additional notes or special instructions for the reservation",
                null=True,
            ),
        ),
    ]
